### ISSUE TITLE
1.6.2 Final Release Checklist

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1134]
This is the final release checklist for 1.6.2 in the next week or two. 

Tagging @mortfell @jpcima @VincyZed  @tank-trax

- [x] Manual Updates #954 
- [x] Stand-alone 16 bit normalized #1078 
- [x] Import patches from @mortfell
- [x] Import the claes patches oddy found
- [x] patches with and vs And
- [x] menu item links to https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Additional-Content
- [x] Scan and reclassify or close any other issues in 1.6.2 milestone [here]
(https://github.com/surge-synthesizer/surge/milestone/4)
- [x] Add the Emu patches which are in presets-wavetables git channel
- [x] Add the Emu fixes for VSCO which are in the same
- [x] LV2 in the README
- [x] Update website to say “LV2” under linux
- [x] Link website to wikis
- [x] Push https://github.com/surge-synthesizer/surge-synthesizer.github.io/pull/100 to master to effect website changes
- [x] Finalize Changelog
- [x] CHangeLog title explicitly mentions 1.6.2
- [x] create release branch and push; wait for release builds
- [x] check release builds
- [x] update home-brew (and this time, document how to update home-brew)
- [x] Announce On KVR (@baconpaul) and Facebook (@tank-trax)
- [x] Say “yay” and close this issue.

For what's up after this release, #1117 explains where @baconpaul is gonna spend a lot of his fall; and also we need to scan and classify all the open issues to sort of clean up the tagging and freshness.

**Comment by jpcima** [comment]
The LV2 could receive a mention in README as well.

**Comment by baconpaul** [comment]
Great point yup.

**Comment by gnips** [comment]
Don't forget the "About" box :)

**Comment by baconpaul** [comment]
The "About" box auto-updates at build time. If you build on a branch our CI pipeline will replace the text for us automatically! (but that's one thing to test when we check out the builds :) )

**Comment by baconpaul** [comment]
Closing this issue. It's just telling a broader user base about it now. 

Thanks all!
