### ISSUE TITLE
1.6.3 Release Checklist

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1233]
Planning a 1.6.3 release in early November, primarily fixing VST3 bugs but also some quality of life stuff. 

- [x] Address all [open issues](https://github.com/surge-synthesizer/surge/milestone/5) for the milestone
- [x] Move the surge-fx pointer and push
- [x] Update the changelog
- [x] Update Manual
     - [x] https://www.kvraudio.com/forum/viewtopic.php?t=511921&start=105
     - [x] Distortion Changes
- [x] Tag with branch `release/1.6.3`
- [x] Update homebrew
- [x] Announce in various forums
