### ISSUE TITLE
Release Checklist for version 1.6.4

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1258]
Release label: 1.6.4
Target Release Date: Dec 2019

- [x] Address all open issues for the milestone [here](https://github.com/surge-synthesizer/surge/milestone/11)
- [x] Update the changelog
- [x] Update Manual
   - [x] release velocity stuff
   - [x] distortion drive
- [x] Tag with branch release/1.6.4
- [x] Update and Announce
  - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
  - [x] Post to KVR thread, Facebook, Slack etc
  - [x] Notify sonisto at rune.braager@sonisto.com
