### ISSUE TITLE
Release Checklist for version 1.6.4.1

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1346]
Release label: 1.6.4.1
Target Release Date: Next few days 
Milestone

- [x] Fix the catalina installer
- [x] Include new content from Damon
- [x] Update the changelog
- [x] Create git markers
  - [x] create a branch named `release/1.6.4.1`
  - [x] sign a tag with `git tag -s release_1.6.4.1 -m "Create signed tag"`
  - [x] push both the branch and tag to upstream
- [x] Update and Announce
   - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [x] Post to KVR thread, Facebook, Slack etc
   - [x] Notify sonisto at rune.braager@sonisto.com
