### ISSUE TITLE
Release Checklist for version 1.6.5

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1390]
Release label: 1.6.5
Target Release Date: February 2020
Milestone https://github.com/surge-synthesizer/surge/milestone/12

- [x] Address all open issues for the milestone https://github.com/surge-synthesizer/surge/milestone/12
- [x] a few specific tests
   - [x] Make sure the ok dialog says ok on windows and linux from the wavetable export
   - [x] AEG/FEG on Win32Bit with the LFO
- [x] Move the surge-fx pointer and push. Gotta do this this time because of the delay bug
- [ ] Move the surge-rack pointer and update rack. Ditto
- [x] Update the changelog
- [x] Update Manual
- [x] Create git markers
  - [x] create a branch named `release/1.6.5` 
  - [x] sign a tag with `git tag -s release_1.6.5 -m "Create signed tag"`
  - [x] push both the branch and tag to upstream
- [x] Update and Announce
   - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [x] Post to KVR thread, Facebook, Slack etc
   - [x] Notify sonisto at updates@sonisto.com
