### ISSUE TITLE
Release Checklist for version 1.6.6

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1544]
Release label: 1.6.6
Target Release Date: Late Spring 2020 
Milestone: https://github.com/surge-synthesizer/surge/milestone/13

- [x] Address all open issues for the milestone
- [x] Move the surge-fx pointer and push
- [x] Move the surge-rack pointer and update rack
- [x] Update the changelog
- [x] Update Manual
- [x] Create git markers
  - [x] create a branch named `release/1.6.6`
  - [x] sign a tag with `git tag -s release_1.6.6 -m "Create signed tag"`
  - [x] push both the branch and tag to upstream
- [x] Update and Announce
   - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [x] Post to KVR thread, Facebook, Slack etc
   - [x] Notify sonisto at updates@sonisto.com
   - [x] Open a KX issue https://github.com/KXStudio/Repository/issues
