### ISSUE TITLE
Release Checklist for 1.7.0

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1778]
Release label: 1.7.0
Target Release Date: Widespread beta with the nightlies July 2020, Release Aug 2020
Milestone

- [x] Address all open issues for the milestone https://github.com/surge-synthesizer/surge/milestone/14
- [x] upgrade surge-fx to juce6
- [x] move surge-fx to proper juce6
- [x] Move the surge-fx pointer and push
- [x] Move the surge-rack pointer and update rack
- [x] make some patches using the new features
- [x] Update the changelog
- [x] Update Manual
- [x] Update the web site with "Looking for a 1.6 release?" with a link to a page we create.
- [x] Create git markers
  - [x] create a branch named `release/1.7.0` or whatnot
  - [x] sign a tag with `git tag -s release_1.7.0 -m "Create signed tag"`
  - [x] push both the branch and tag to upstream
- [ ] Update and Announce
   - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [x] Post to KVR thread, Facebook, Slack etc
   - [x] Notify sonisto at rune.braager@sonisto.com
   - [x] let @falkTX know over on KX
