### ISSUE TITLE
Midi Learn / CC / Mapping save, restore, and bugs

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1994]
This is a master issue spanning #1929 #1774 #1678 #584 which are all discussing various inadequacies of how we store midi mappings. Some comments

- [x] We try to save in configuration.xml. That's a mistake so remove that code (since configuration.xml is both global and, on mac and linux and many windows, non-user-writable). So step one is modify `SurgeStorage::save_midi_controllers` to at least save to something in userspace
- [x] We don't save to the patch for CCs. This is the first mod wheel part of #1929 
- [x] We don't save to DAW settings. So take the midi controller mapping and add it to the daw extra state. This is the essence of #1774 and the first half of #1678 
- [x] We can add a regtest for the controller daw state
- [x] Allow user-specific named saves of midi configurations, much like we just added with FX. This is the essence of #584 and the second half of #1678 
- [x] Fix the midi learn mis-map with the AU in #2072
- [x] Then make sure that the rest of #1929 (which also has a param collision problem) gets sorted

So lemme put this here so I don't have to hop between all those issues while I implement some of this stuff.
