### ISSUE TITLE
Release Checklist for version 1.7.1

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2381]
Release label: 1.7.1
Target Release Date: Early Sept 2020 maybe? if we make it small 
Milestone https://github.com/surge-synthesizer/surge/milestone/18

- [x] Address all open issues for the milestone https://github.com/surge-synthesizer/surge/milestone/18
- [x] Push harder issues to 1.7.2 once we decide what's in
- [x] Move the surge-fx pointer and push
- [x] Move the surge-rack pointer and update rack
- [x] Update the changelog
- [x] Update Manual
- [x] Create git markers
  - [x] create a branch named `release/1.7.1` 
  - [x] sign a tag with `git tag -s release_1.7.1 -m "Create signed tag"`
  - [x] push both the branch and tag to upstream
- [x] Update and Announce
   - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [x] Post to KVR thread, Facebook, Slack etc
   - [x] Notify sonisto at rune.braager@sonisto.com
