### ISSUE TITLE
Release Checklist for version 1.8.0

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2413]
Release label: 1.8.0
Target Release Date: Jan 2021
Milestone https://github.com/surge-synthesizer/surge/milestone/19

- [x] Address all open issues for the milestone https://github.com/surge-synthesizer/surge/milestone/19
- [x] Give falk an early ping so he can pre-check build
- [x] Move the surge-fx pointer and push
- [x] Update changelog
- [x] Update manual
- [x] Include all new content
- [x] Create git markers
  - [x] create a branch named `release/1.8.0` 
  - [x] sign a tag with `git tag -s release_1.8.0 -m "Create signed 1.8.0 tag"` probably after running `gpg --output x.sig --sign CMakeLists.txt` to open your gpg sig again
  - [x] push both the branch and tag to upstream
- [x] Update and Announce
   - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [x] Post to KVR thread, Facebook, Discord, etc.

**Comment by mortfell** [comment]
Just writing this here so that I can hold myself to it, I'm planning to finally have the Quickstart guide I started way back be done for this release.

And also update the presets and wavetables I made by this time...... there is a handful of things I'd like to change and improve with them.

**Comment by baconpaul** [comment]
Cool and good to see you again! My guess is late dec early Jan time scale so we have time

**Comment by mortfell** [comment]
Ok great, yeah that seems realistic.
Yes I've been very busy with a new job, but I still use Surge almost everyday :)
Very exciting to see how many people have gotten involved and how many new updates/features there has been

**Comment by baconpaul** [comment]
Yeah try the vintage filters ... they are fun... and more soon too
