### ISSUE TITLE
2020-08 New logo deployment checklist

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#2483]
A list of logo tasks, and variants for places that our branding is used.
- [x] Design the core logo variants
  - tall rectangle, for full logo only
  - square, for icons and tight spaces.
  - descriptive logo, rectangular, with accompanying text.

Places to update (in priority order):
- [x] GitHub landing page: https://surge-synthesizer.github.io/
- [x] Plugin UI: About splash page
- [x] Plugin UI: main interface
- [x] Docs: landing page
- [x] Facebook
- [x] YouTube channel
- [ ] Docs: other pages prominently featuring the logo
- [ ] Other plugins in the suite (modules, light touch on other FOSS in the family?).
- [x] Windows installer
- [x] Mac installer
- [x] Forum sections/threads (KVR, ...?)
- [x] GitHub logo
- [x] Discord
- [ ] Slack

Given that only the author can edit this, I'll monitor the comments for changes until done.

**Comment by baconpaul** [comment]
Can we attach the final logo assets to this ticket? I can do YouTube, GitHub, and KVR.

The mark on the plugin is just adding the asset to the background SVGs.

We also need to think about https://surge-synth-team.org and how this fits

**Comment by mkruselj** [comment]
Here's the .sketch file that contains the full logo and favicon (squared off S on black background, good for avatars).


[Surge Logo.zip](https://github.com/surge-synthesizer/surge/files/5081425/Surge.Logo.zip)

**Comment by funkaloss** [comment]
Nice one! I wonder if the corners are supposed to be symmetrically rounded. They don't seem to be now.

**Comment by mkruselj** [comment]
That may be because I scrunched it from the rectangle form to square form for favicon. When it's sized down to fit avatars etc. it'd not really be noticeable I'd say.

**Comment by baconpaul** [comment]
Mac installer: https://stackoverflow.com/questions/45381740/how-to-programmatically-preferably-bash-add-icon-to-dmg

**Comment by kzantow** [comment]
Might also add a link to the best resources in code in case someone finds this ticket, like here: https://github.com/surge-synthesizer/surge/blob/main/installer_mac/Resources/SurgeLogo.png ?

**Comment by baconpaul** [comment]
I think we would be done here except for @kzantow comment. We should really have the original assets for the logo (an SVG and a variety of resolution PNGs) in the repo. I don't have em. Can someone who does wrangle them into assets/Logo, do a PR, and then close this issue? Thanks!

**Comment by mkruselj** [comment]
Will do.

**Comment by mkruselj** [comment]
@j5v We're pretty much done with this, can check off all the boxes. 🙂
