### ISSUE TITLE
Release Checklist for version 1.8.1

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3652]
Release label: 1.8.1
Target Release Date: Jan 24 2021 
Milestone

Bugs happen you know? So lets do a cleanup a week after 180

- [x] Address all open issues for the milestone https://github.com/surge-synthesizer/surge/milestone/21
- [x] Update the changelog
- [x] Create git markers
  - [x] create a branch named `release/1.8.1` or whatnot
  - [x] sign a tag with `git tag -s release_1.8.1 -m "Create signed tag"`
  - [x] push both the branch and tag to upstream
- [x] Update and Announce
   - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [ ] Post to KVR thread, Facebook, Slack etc
