### ISSUE TITLE
Release Checklist for version 1.9

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3745]
Release label: 1.9
Target Release Date: April 
Milestone: https://github.com/surge-synthesizer/surge/milestone/20

- [x] Address all open issues for the milestone https://github.com/surge-synthesizer/surge/milestone/20
- [x] Update the changelog
- [x] Update the manual
- [x] Create git markers
  - [x] Create a branch named `release/1.9.0` 
  - [x] Sign a tag with `git tag -s release_1.9.0 -m "Create signed tag"` probably after running `gpg --output x.sig --sign CMakeLists.txt` to open your GPG sig again
  - [x] Push both the branch and tag to upstream
- [x] Update and announce
   - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [x] Post to KvR thread, add KvR news entry, Facebook, Discord, etc.
