### ISSUE TITLE
DPW Tracking Issue

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#3910]
Waveforms with second derivative's of a cubic polynomial.

This is just a tracking issue for baconpaul since he thought to merge a first draft.

Known problems now are

- [x] Renaming the multi- with that FIXME is odd
- [x] Default dlck values now that things are bipolar
- [x] The menu glyph doesn't show up
- [x] Performance edit the code
