### ISSUE TITLE
Release Checklist for Surge XT 1.0

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4303]
Release label: Surge XT 1.0
Target Release Date: September or October 2021
Milestone: https://github.com/surge-synthesizer/surge/milestone/24

- [ ] Address all open issues for the milestone https://github.com/surge-synthesizer/surge/milestone/24
- [ ] Update the changelog
- [ ] Update the manual
- [ ] Create git markers
  - [ ] Create a branch named `release/1.9.0` 
  - [ ] Sign a tag with `git tag -s release_1.9.0 -m "Create signed tag"` probably after running `gpg --output x.sig --sign CMakeLists.txt` to open your GPG sig again
  - [ ] Push both the branch and tag to upstream
- [ ] Update and announce
   - [ ] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [ ] Post to KvR thread, add KvR news entry, Facebook, Discord, etc.
Milestone

**Comment by Bleuzen** [comment]
Hi, will SurgeXT be backwards compatible to Surge? Only found this so far:
https://github.com/surge-synthesizer/surge/issues/5429#issuecomment-974094795

> We replatformed surge in juce and added features. To do that we had to break some comparability points so we gave the plugin and project a new name “surge xt” and it installs distinct from and side by side with surge

@baconpaul 

Not sure if you meant "comparability points" or "compatibility points". Hope this was a typo, but seems this means it won't be backwards compatible?
This would be really sad :/

Means packages have to maintain two separate versions and users have to keep two separate versions installed as well (to keep older projects working).
Hope to see SurgeXT as dropin replacement for Surge. Is there still hope?

**Comment by baconpaul** [comment]
the plugin id has to change.
fxp are compatible. but daw sessions are not.

**Comment by baconpaul** [comment]
from our faq on discord:

SurgeXT is the next version of Surge. Right now the nightlies are a stable version of XT, and we are now in a beta test period with a release targeted in Jan 2022. To try the XT beta, please check out the builds in the surge-nightlies channel.

Surge was open sourced in 2018 and had a set of reasonable but distinct architectural choices. We were able to do a lot with that, both getting that version working then adding all the features in 1.7, 1.8 and 1.9. But although Surge was and is great software to work on, we eventually realized we had hit a bit of a brick wall with some of the ways Surge worked (specifically: hand-rolled plugin wrappers and the VSTGUI ui, but other stuff too). So we decided to begin work to port Surge to Juce. This project is "Surge XT".

Surge XT has a great set of new features already, including a greatly expanded waveshaper section, a formula modulator, great modulation overview tools, an expanded tuning ui, expanded and new FX, and much more. You should give it a whirl! Since it installs with a different plugin ID and different resource directories, you can safely run it side by side with Surge 1.9.

**Comment by baconpaul** [comment]
@hfiguiere we released XT 1.0 today if you want to see if flatpack works for you with it.

**Comment by hfiguiere** [comment]
> @hfiguiere we released XT 1.0 today if you want to see if flatpack works for you with it.

I'll try later today - I already have a build from a few days ago. 

I didn't even the announcement notification :-/

**Comment by baconpaul** [comment]
> I didn't even the announcement notification :-/

The announcements are rolling out to various social medias over the next day or two.

**Comment by hfiguiere** [comment]
I was talking about github notifying me of a new release, but then I realize you only do tags.

**Comment by baconpaul** [comment]
Oh yeah. tag and branch here; release over in https://github.com/surge-synthesizer/releases-xt/
