### ISSUE TITLE
Index Modulators (sub-issue of Formula Modulator)

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4868]
The formula modulator can produce vector valued outputs and so, in theory, the modulator can be vector valued. You then want to route different indices etc...

I started this in  64c4a4125a6f but never wrote it up in an issue so this does that

first the get_output has an index on the modulation source and there's an index count. Cool. That's there now

In order, probably as several commits

- [x] Step 1: get to a point where the APIs are complete
  - [x] Add a source_id to ModulationRouting and stream it
  - [x] Make the construction of local copy use the routing source_id
  - [x] For each of the getModRouting and the like calls in SurgeSynthesizer add an index argument (and while at it make them const)
- [x] Step 2: Make the formula modulator create a vector output, even if you can't route it with the UI
  - [x] Note I can construct it by hand with various hacks to the xml and data structures if I save a patch to test
- [ ] Step 3: Update the UI with a hamburger; consider the alternates issue along the way. Clean up.
  - [ ] especially important is what happens if I toggle from formula to sin or what not; do we collapse it to single value? I think yes (that is, the other modulation sources just ignore index rather than throw an error) but this is up in the air.

**Comment by baconpaul** [comment]
I bet this issue will close #2678 along the way
