### ISSUE TITLE
Release Checklist for Surge XT 1.1

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5786]
Release label: XT 1.1.0
Target Release Date: 
Milestone: https://github.com/surge-synthesizer/surge/milestone/25

- [x] Address all open issues for the milestone
- [x] Update the changelog
- [x] Update Manual
- [x] Create git markers
  - [x] create a branch named `release-xt/1.1.0` 
  - [x] sign a tag with `git tag -s release_xt_1.1.0 -m "Create signed tag"` probably after running `gpg --output x.sig --sign CMakeLists.txt` to open your GPG sig again
  - [x] push both the branch and tag to upstream
- [x] Update and Announce
   - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) but remember this time I have changed com.surge to org.surge and added a CLAP so we need to adjust
   - [x] Post to KVR thread, Facebook, Slack etc

**Comment by mxmilkiib** [comment]
Having essentially two items of software in the one repo with a separate and conflicting versioning scheme is going to be a bit tricky to manage with for packagers and people trying to parse the releases information. How about the possibility of bumping the major version number rather than resetting the version number, or having a separate repo for the reworked version?

**Comment by baconpaul** [comment]
We didn’t want to split the repo. There’s no reason to - the versions are linear forward evolutions.

we have signed tags for every released version.
