### ISSUE TITLE
Release checklist for Surge XT 1.1.1

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6476]
Release label: XT 1.1.1
Link to milestone: https://github.com/surge-synthesizer/surge/milestone/28

- [x] Address all reasonable subset of the 1.1.n issues 
- [x] Update the changelog
- [x] Update the manual
- [x] Create git markers
  - [x] create a branch named `release-xt/1.1.1`
  - [x] sign a tag with `git tag -s release_xt_1.1.1 -m "Create signed tag"`, probably after running `gpg --output x.sig --sign CMakeLists.txt` to open your GPG sig again
  - [x] push both the branch and tag to upstream
- [x] Update and announce
   - [x] Update home-brew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [x] Post to KvR thread, Facebook, Discord, etc.
