### ISSUE TITLE
Release checklist for Surge XT 1.1.2

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#6574]
Release label: XT 1.1.2
Link to milestone: https://github.com/surge-synthesizer/surge/milestone/30

- [ ] Address all open issues for the milestone
- [ ] Update the changelog
- [ ] Update the manual
- [ ] Create git markers
  - [ ] Create a branch named `release-xt/1.1.2`
  - [ ] Sign a tag with `git tag -s release_xt_1.1.2 -m "Create signed tag"`, probably after running `gpg --output x.sig --sign CMakeLists.txt` to open your GPG sig again
  - [ ] Push both the branch and tag to upstream
- [ ] Update and announce
   - [ ] Update homebrew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [ ] Post to KvR thread, Facebook, Discord, etc.
