### ISSUE TITLE
Release checklist for Surge XT 1.2.0

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6678]
Release label: XT 1.2.0
Link to milestone: https://github.com/surge-synthesizer/surge/milestone/31

- [x] Address all open issues for the milestone
- [x] Update the changelog
- [x] Update the manual
- [x] Update CMakeLists project version
- [x] Create git markers
  - [x] Create a branch named `release-xt/1.1.3`
  - [x] Sign a tag with `git tag -s release_xt_1.1.3 -m "Create signed tag"`, probably after running `gpg --output x.sig --sign CMakeLists.txt` to open your GPG sig again
  - [x] Probably rev the azure pipeline in release side to work around that tag bug
  - [x] Push both the branch and tag to upstream
- [ ] Update and announce
   - [ ] Update homebrew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [x] Post to KvR thread, Facebook, Discord, etc.

**Comment by Andreya-Autumn** [comment]
All 1.2 issues (and some 1.2.1 ones) closed! 🥳 
And once I rewrite the tuning manual updates my dumb*** accidentally deleted, the manual updates will be done too.
