### ISSUE TITLE
Release checklist for Surge XT 1.2.1

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6925]
Release label: XT 1.2.1
Link to milestone: https://github.com/surge-synthesizer/surge/milestone/32

## Pre Install

- [ ] Address all open issues for the milestone
- [ ] Update the changelog
- [ ] Update the manual
- [ ] Make sure the `CMakeLists.txt` version matches the version you are about to install

## Executing the install

- [ ] Update the releases-xt/azure-pipelines so we don't get a tag conflict when the release happens even 
      if it is just a bump commit
- [ ] Create git markers in the surge repo
  - [ ] Unlock your GPG key in case,running `gpg --output x.sig --sign CMakeLists.txt` 
  - [ ] Create a branch named `git checkout -b release-xt/1.2.1`
  - [ ] Sign a tag with `git tag -s release_xt_1.2.1 -m "Create signed tag"`, 
  - [ ] Push both the branch and tag to upstream `git push --atomic upstream-write release-xt/1.2.1 release_xt_1.2.1` 

## Post Install

- [ ] Update and announce
   - [ ] Update homebrew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc) 
   - [ ] Post to KvR thread, Facebook, Discord, etc.

**Comment by mthierman** [comment]
- [ ] Update [Winget manifest](https://github.com/microsoft/winget-pkgs)

Example updating v1.2.3:

```wingetcreate update --urls https://github.com/surge-synthesizer/releases-xt/releases/download/1.2.3/surge-xt-win64-1.2.3-setup.exe --version 1.2.3 SurgeSynthTeam.SurgeXT```

```wingetcreate update --submit --urls https://github.com/surge-synthesizer/releases-xt/releases/download/1.2.3/surge-xt-win64-1.2.3-setup.exe --version 1.2.3 SurgeSynthTeam.SurgeXT```
