### ISSUE TITLE
Release checklist for Surge XT 1.3.1

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#7377]
Release label: XT 1.3.1
Link to milestone: https://github.com/surge-synthesizer/surge/milestone/33

## Pre-Install

- [x] Address all open issues for the milestone
- [x] Update the changelog
- [x] Update the manual
- [x] Make sure the `CMakeLists.txt` version matches the version you are about to install

## Executing the Install

- [x] Update `releases-xt/azure-pipelines` so we don't get a tag conflict when the release happens even if it is just a bump commit
- [x] Create git markers in the `surge` repository
  - [x] Unlock your GPG key just in case, by running `gpg --output x.sig --sign CMakeLists.txt`
  - [x] Create a branch named `git checkout -b release-xt/1.3.1`
  - [x] Sign a tag with `git tag -s release_xt_1.3.1 -m "Create signed tag"`,
  - [x] Push both the branch and tag to upstream `git push --atomic upstream-write release-xt/x.y.z release_xt_1.3.1`

## Post-Install

- [x] Update and announce
   - [x] Update Homebrew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc)
   - [x] Update [Winget manifest](https://github.com/microsoft/winget-pkgs) (`wingetcreate update --submit --urls https://github.com/surge-synthesizer/releases-xt/releases/download/1.3.1/surge-xt-win64-1.3.1-setup.exe --version x.y.z SurgeSynthTeam.SurgeXT`)
   - [x] Ping @luzpaz in https://github.com/surge-synthesizer/surge/issues/7132
   - [x] Post to KvR thread, Facebook, Discord, etc.
