### ISSUE TITLE
Release checklist for Surge XT 1.4

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7782]
Release label: XT 1.4.0
Link to milestone: https://github.com/surge-synthesizer/surge/milestone/36

## Pre-Install

- [ ] Address all open issues for the milestone
- [ ] Go through the submitted patch banks and select the "best-of" for release 
- [ ] Update the changelog
- [ ] Update the manual
- [ ] Make sure the `CMakeLists.txt` version matches the version you are about to install

## Executing the Install

- [ ] Update `releases-xt/azure-pipelines` so we don't get a tag conflict when the release happens even if it is just a bump commit
- [ ] Create git markers in the `surge` repository
  - [ ] Unlock your GPG key just in case, by running `gpg --output x.sig --sign CMakeLists.txt`
  - [ ] Create a branch named `git checkout -b release-xt/x.y.z`
  - [ ] Sign a tag with `git tag -s release_xt_x.y.z -m "Create signed tag"`,
  - [ ] Push both the branch and tag to upstream `git push --atomic upstream-write release-xt/x.y.z release_xt_x.y.z`

## Post-Install

- [ ] Update and announce
   - [ ] Update Homebrew [doc](https://github.com/surge-synthesizer/surge/tree/master/doc)
   - [ ] Update [Winget manifest](https://github.com/microsoft/winget-pkgs) (`wingetcreate update --submit --urls https://github.com/surge-synthesizer/releases-xt/releases/download/x.y.z/surge-xt-win64-x.y.z-setup.exe --version x.y.z SurgeSynthTeam.SurgeXT`)
   - [ ] Ping @luzpaz in https://github.com/surge-synthesizer/surge/issues/7132
   - [ ] Post to KvR thread, Facebook, Discord, etc.

**Comment by luzpaz** [comment]
JFYI, 1.3.4 is already updated downstream

![Screenshot_20241110_055145](https://github.com/user-attachments/assets/7c0dfc08-6fac-4651-aefc-bb7159180603)
